# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from .tfplugin_pb2 import (
    ApplyResourceChange,
    CallFunction,
    ConfigureProvider,
    GetFunctions,
    GetMetadata,
    GetProviderSchema,
    ImportResourceState,
    MoveResourceState,
    PlanResourceChange,
    ReadDataSource,
    ReadResource,
    StopProvider,
    UpgradeResourceState,
    ValidateDataResourceConfig,
    ValidateProviderConfig,
    ValidateResourceConfig,
)


class ProviderStub:
    """////// Information about what a provider supports/expects"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetadata = channel.unary_unary(
            "/tfplugin6.Provider/GetMetadata",
            request_serializer=GetMetadata.Request.SerializeToString,
            response_deserializer=GetMetadata.Response.FromString,
        )
        self.GetProviderSchema = channel.unary_unary(
            "/tfplugin6.Provider/GetProviderSchema",
            request_serializer=GetProviderSchema.Request.SerializeToString,
            response_deserializer=GetProviderSchema.Response.FromString,
        )
        self.ValidateProviderConfig = channel.unary_unary(
            "/tfplugin6.Provider/ValidateProviderConfig",
            request_serializer=ValidateProviderConfig.Request.SerializeToString,
            response_deserializer=ValidateProviderConfig.Response.FromString,
        )
        self.ValidateResourceConfig = channel.unary_unary(
            "/tfplugin6.Provider/ValidateResourceConfig",
            request_serializer=ValidateResourceConfig.Request.SerializeToString,
            response_deserializer=ValidateResourceConfig.Response.FromString,
        )
        self.ValidateDataResourceConfig = channel.unary_unary(
            "/tfplugin6.Provider/ValidateDataResourceConfig",
            request_serializer=ValidateDataResourceConfig.Request.SerializeToString,
            response_deserializer=ValidateDataResourceConfig.Response.FromString,
        )
        self.UpgradeResourceState = channel.unary_unary(
            "/tfplugin6.Provider/UpgradeResourceState",
            request_serializer=UpgradeResourceState.Request.SerializeToString,
            response_deserializer=UpgradeResourceState.Response.FromString,
        )
        self.ConfigureProvider = channel.unary_unary(
            "/tfplugin6.Provider/ConfigureProvider",
            request_serializer=ConfigureProvider.Request.SerializeToString,
            response_deserializer=ConfigureProvider.Response.FromString,
        )
        self.ReadResource = channel.unary_unary(
            "/tfplugin6.Provider/ReadResource",
            request_serializer=ReadResource.Request.SerializeToString,
            response_deserializer=ReadResource.Response.FromString,
        )
        self.PlanResourceChange = channel.unary_unary(
            "/tfplugin6.Provider/PlanResourceChange",
            request_serializer=PlanResourceChange.Request.SerializeToString,
            response_deserializer=PlanResourceChange.Response.FromString,
        )
        self.ApplyResourceChange = channel.unary_unary(
            "/tfplugin6.Provider/ApplyResourceChange",
            request_serializer=ApplyResourceChange.Request.SerializeToString,
            response_deserializer=ApplyResourceChange.Response.FromString,
        )
        self.ImportResourceState = channel.unary_unary(
            "/tfplugin6.Provider/ImportResourceState",
            request_serializer=ImportResourceState.Request.SerializeToString,
            response_deserializer=ImportResourceState.Response.FromString,
        )
        self.MoveResourceState = channel.unary_unary(
            "/tfplugin6.Provider/MoveResourceState",
            request_serializer=MoveResourceState.Request.SerializeToString,
            response_deserializer=MoveResourceState.Response.FromString,
        )
        self.ReadDataSource = channel.unary_unary(
            "/tfplugin6.Provider/ReadDataSource",
            request_serializer=ReadDataSource.Request.SerializeToString,
            response_deserializer=ReadDataSource.Response.FromString,
        )
        self.GetFunctions = channel.unary_unary(
            "/tfplugin6.Provider/GetFunctions",
            request_serializer=GetFunctions.Request.SerializeToString,
            response_deserializer=GetFunctions.Response.FromString,
        )
        self.CallFunction = channel.unary_unary(
            "/tfplugin6.Provider/CallFunction",
            request_serializer=CallFunction.Request.SerializeToString,
            response_deserializer=CallFunction.Response.FromString,
        )
        self.StopProvider = channel.unary_unary(
            "/tfplugin6.Provider/StopProvider",
            request_serializer=StopProvider.Request.SerializeToString,
            response_deserializer=StopProvider.Response.FromString,
        )


class ProviderServicer:
    """////// Information about what a provider supports/expects"""

    def GetMetadata(self, request, context):
        """GetMetadata returns upfront information about server capabilities and
        supported resource types without requiring the server to instantiate all
        schema information, which may be memory intensive. This RPC is optional,
        where clients may receive an unimplemented RPC error. Clients should
        ignore the error and call the GetProviderSchema RPC as a fallback.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProviderSchema(self, request, context):
        """GetSchema returns schema information for the provider, data resources,
        and managed resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateProviderConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateResourceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateDataResourceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpgradeResourceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConfigureProvider(self, request, context):
        """////// One-time initialization, called before other functions below"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadResource(self, request, context):
        """////// Managed Resource Lifecycle"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PlanResourceChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApplyResourceChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ImportResourceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MoveResourceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadDataSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFunctions(self, request, context):
        """Functions

        GetFunctions returns the definitions of all functions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CallFunction(self, request, context):
        """CallFunction runs the provider-defined function logic and returns
        the result with any diagnostics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopProvider(self, request, context):
        """////// Graceful Shutdown"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProviderServicer_to_server(servicer: ProviderServicer, server: grpc.Server):
    rpc_method_handlers = {
        "GetMetadata": grpc.unary_unary_rpc_method_handler(
            servicer.GetMetadata,
            request_deserializer=GetMetadata.Request.FromString,
            response_serializer=GetMetadata.Response.SerializeToString,
        ),
        "GetProviderSchema": grpc.unary_unary_rpc_method_handler(
            servicer.GetProviderSchema,
            request_deserializer=GetProviderSchema.Request.FromString,
            response_serializer=GetProviderSchema.Response.SerializeToString,
        ),
        "ValidateProviderConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateProviderConfig,
            request_deserializer=ValidateProviderConfig.Request.FromString,
            response_serializer=ValidateProviderConfig.Response.SerializeToString,
        ),
        "ValidateResourceConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateResourceConfig,
            request_deserializer=ValidateResourceConfig.Request.FromString,
            response_serializer=ValidateResourceConfig.Response.SerializeToString,
        ),
        "ValidateDataResourceConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateDataResourceConfig,
            request_deserializer=ValidateDataResourceConfig.Request.FromString,
            response_serializer=ValidateDataResourceConfig.Response.SerializeToString,
        ),
        "UpgradeResourceState": grpc.unary_unary_rpc_method_handler(
            servicer.UpgradeResourceState,
            request_deserializer=UpgradeResourceState.Request.FromString,
            response_serializer=UpgradeResourceState.Response.SerializeToString,
        ),
        "ConfigureProvider": grpc.unary_unary_rpc_method_handler(
            servicer.ConfigureProvider,
            request_deserializer=ConfigureProvider.Request.FromString,
            response_serializer=ConfigureProvider.Response.SerializeToString,
        ),
        "ReadResource": grpc.unary_unary_rpc_method_handler(
            servicer.ReadResource,
            request_deserializer=ReadResource.Request.FromString,
            response_serializer=ReadResource.Response.SerializeToString,
        ),
        "PlanResourceChange": grpc.unary_unary_rpc_method_handler(
            servicer.PlanResourceChange,
            request_deserializer=PlanResourceChange.Request.FromString,
            response_serializer=PlanResourceChange.Response.SerializeToString,
        ),
        "ApplyResourceChange": grpc.unary_unary_rpc_method_handler(
            servicer.ApplyResourceChange,
            request_deserializer=ApplyResourceChange.Request.FromString,
            response_serializer=ApplyResourceChange.Response.SerializeToString,
        ),
        "ImportResourceState": grpc.unary_unary_rpc_method_handler(
            servicer.ImportResourceState,
            request_deserializer=ImportResourceState.Request.FromString,
            response_serializer=ImportResourceState.Response.SerializeToString,
        ),
        "MoveResourceState": grpc.unary_unary_rpc_method_handler(
            servicer.MoveResourceState,
            request_deserializer=MoveResourceState.Request.FromString,
            response_serializer=MoveResourceState.Response.SerializeToString,
        ),
        "ReadDataSource": grpc.unary_unary_rpc_method_handler(
            servicer.ReadDataSource,
            request_deserializer=ReadDataSource.Request.FromString,
            response_serializer=ReadDataSource.Response.SerializeToString,
        ),
        "GetFunctions": grpc.unary_unary_rpc_method_handler(
            servicer.GetFunctions,
            request_deserializer=GetFunctions.Request.FromString,
            response_serializer=GetFunctions.Response.SerializeToString,
        ),
        "CallFunction": grpc.unary_unary_rpc_method_handler(
            servicer.CallFunction,
            request_deserializer=CallFunction.Request.FromString,
            response_serializer=CallFunction.Response.SerializeToString,
        ),
        "StopProvider": grpc.unary_unary_rpc_method_handler(
            servicer.StopProvider,
            request_deserializer=StopProvider.Request.FromString,
            response_serializer=StopProvider.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("tfplugin6.Provider", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Provider:
    """////// Information about what a provider supports/expects"""

    @staticmethod
    def GetMetadata(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/GetMetadata",
            GetMetadata.Request.SerializeToString,
            GetMetadata.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetProviderSchema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/GetProviderSchema",
            GetProviderSchema.Request.SerializeToString,
            GetProviderSchema.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ValidateProviderConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/ValidateProviderConfig",
            ValidateProviderConfig.Request.SerializeToString,
            ValidateProviderConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ValidateResourceConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/ValidateResourceConfig",
            ValidateResourceConfig.Request.SerializeToString,
            ValidateResourceConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ValidateDataResourceConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/ValidateDataResourceConfig",
            ValidateDataResourceConfig.Request.SerializeToString,
            ValidateDataResourceConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpgradeResourceState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/UpgradeResourceState",
            UpgradeResourceState.Request.SerializeToString,
            UpgradeResourceState.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ConfigureProvider(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/ConfigureProvider",
            ConfigureProvider.Request.SerializeToString,
            ConfigureProvider.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ReadResource(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/ReadResource",
            ReadResource.Request.SerializeToString,
            ReadResource.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PlanResourceChange(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/PlanResourceChange",
            PlanResourceChange.Request.SerializeToString,
            PlanResourceChange.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ApplyResourceChange(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/ApplyResourceChange",
            ApplyResourceChange.Request.SerializeToString,
            ApplyResourceChange.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ImportResourceState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/ImportResourceState",
            ImportResourceState.Request.SerializeToString,
            ImportResourceState.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def MoveResourceState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/MoveResourceState",
            MoveResourceState.Request.SerializeToString,
            MoveResourceState.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ReadDataSource(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/ReadDataSource",
            ReadDataSource.Request.SerializeToString,
            ReadDataSource.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetFunctions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/GetFunctions",
            GetFunctions.Request.SerializeToString,
            GetFunctions.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CallFunction(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/CallFunction",
            CallFunction.Request.SerializeToString,
            CallFunction.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def StopProvider(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tfplugin6.Provider/StopProvider",
            StopProvider.Request.SerializeToString,
            StopProvider.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
